icons_format = "{icon}"

[theme]
theme = "solarized-dark"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["ó°‚","ó°»","ó°¾","ó°‚","ó°¹"]
bat_charging = "ó°‚„"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
[block.mappings]
"Spanish (N/A)" = "ğŸ‡ªğŸ‡¸"
"English (US)" = "ğŸ‡ºğŸ‡¸"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2)"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2)"
format_alt = " $icon_swap $swap_used_percents.eng(w:2)"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = "$icon $percentage"
full_format = "$icon $percentage"
charging_format = "$icon $percentage"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
